### ISSUE TITLE
An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by lsnpatryks** [lsnova/angular.modules#5]
```
ERROR in node_modules/@lsnova/angularmodules/lib/directives/numeric/numeric.directive.d.ts(20,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@lsnova/angularmodules/lib/directives/numeric/numeric.directive.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@lsnova/angularmodules/lib/services/lsn-cross-tab/lsn-cross-tab.service.d.ts(15,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@lsnova/angularmodules/lib/services/lsn-cross-tab/lsn-cross-tab.service.d.ts(24,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@lsnova/angularmodules/lib/services/lsn-cross-tab/lsn-cross-tab.service.d.ts(43,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@lsnova/angularmodules/lib/services/lsn-cross-tab/lsn-cross-tab.service.d.ts(44,17): error TS1086: An accessor cannot be declared in an ambient context.
```

jak podbiłem w jednej apce do 0.7.9. Można to obejść przez `"skipLibCheck": true,` w `tsconfig.json` ale pewnie warto to poprawić

**Comment by lsnKarolW** [comment]
Hej, w Corpo nie mamy błędów z wersją 0.7.9, czy błąd pojawił się przy przejściu z 0.7.8->0.7.9? Jaką wersję angulara i typescriptu macie w tej apce?

**Comment by lsnpatryks** [comment]
podbiłem się z 0.6.14 do 0.7.9, angulara mamy 8, typescript 3.4.3 - ale z tego co zauważyłem, to problemu pod samym angular 8 (jak robie `./node_modules/.bin/ng serve`) nie ma, pojawia się pod angular 11, który mam globalnie zainstalowany

**Comment by lsnKarolW** [comment]
Sprawdziłem w testowym projekcie z angularem 11, nie mam błędu. Z tego co wiem, jeśli globalny @angular/cli ma wyższą wersję niż lokalny (w projekcie), to lokalna wersja jest używana. Tutaj bardziej chodzi o wersję Typescripta: od wersji 3.7 (angular 9), pojawiła się zmiana w generowaniu plików deklaracyjnych, która powoduje powyższy błąd. W tej chwili jedynyi rozwiązaniami są: podbić angulara do minimum 9 (z Typescriptem >= 3.7), lub ustawić wspomniane przez ciebie `"skipLibCheck": true`. W celu dalszej diagnozy musiałbym sprawdzić aplikację.

**Comment by lsnpatryks** [comment]
oki, zamykam :)
